package TodoDSL.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;

public class TodoList {

  private static void createListGUI() {
    JFrame frame = new JFrame();
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    JTable table = createDataTable();
    addClickingListener(table, frame);

    JPanel panel = new JPanel();
    panel.add(new JLabel("today"));

    frame.add(panel, BorderLayout.NORTH);
    frame.add(new JScrollPane(table), BorderLayout.CENTER);

    frame.setBackground(Color.RED);
    panel.setBackground(Color.RED);
    table.setBackground(Color.RED);

    frame.setTitle(String.format("%s tasks done, %s tasks total", 0, table.getRowCount()));
    frame.setSize(500, 500);
    frame.setMinimumSize(new Dimension(500, 500));
    frame.pack();
    frame.setVisible(true);
  }

  private static JTable createDataTable() {
    String[] columns = new String[]{"name", "description", "priority", "is done yet?"};

    Object[][] data = new Object[][]{{"name", "asda", "LOW", false}, {"xyz", "asd", "LOW", false}, {"asd", "dsa", "LOW", false}};

    return TodoList.fillUpTheTable(data, columns);
  }

  private static JTable fillUpTheTable(Object[][] data, String[] columns) {
    DefaultTableModel model = new DefaultTableModel(data, columns);
    return new JTable(model) {
      public Class getColumnClass(int column) {
        switch (column) {
          case 0:
            return String.class;
          case 1:
            return String.class;
          case 2:
            return String.class;
          case 3:
            return Boolean.class;
          default:
            return String.class;
        }
      }
    };
  }

  public static void addClickingListener(final JTable table, final JFrame frame) {
    table.addMouseListener(new MouseAdapter() {
      public void mouseClicked(MouseEvent evt) {
        Integer taskCount = table.getRowCount();

        Integer doneTasks = 0;

        for (int i = 0; i < taskCount; i++) {
          if (Boolean.parseBoolean(table.getValueAt(i, 3).toString())) {
            doneTasks++;
          }
        }
        frame.setTitle(String.format("%s tasks done, %s tasks total", doneTasks, taskCount));
      }
    });
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        createListGUI();
      }
    });
  }
}
