package TodoDSL.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;

public class TodoList {


  private static void createAndShowGUI() {
    JFrame frame = new JFrame("name");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    JLabel label = new JLabel("hello world");
    frame.getContentPane().add(label);

    frame.add(new JScrollPane(createDataTable()));

    frame.pack();
    frame.setSize(500, 500);
    frame.setMinimumSize(new Dimension(500, 500));
    frame.setVisible(true);
  }

  private static JTable createDataTable() {
    String[] columns = new String[]{"name", "description", "priority", "is done yet?"};
    Object[][] data = new Object[][]{{"xyz", "xyz", "xyz", false}, {"asd", "asd", "asd", false}};
    DefaultTableModel model = new DefaultTableModel(data, columns);
    JTable table = new JTable(model) {

      public Class getColumnClass(int column) {
        switch (column) {
          case 0:
            return String.class;
          case 1:
            return String.class;
          case 2:
            return String.class;
          case 3:
            return Boolean.class;
          default:
            return String.class;
        }
      }
    };
    return table;
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        createAndShowGUI();
      }
    });
  }
}
