package TodoDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptTodo = createDescriptorForTodo();
  /*package*/ final ConceptDescriptor myConceptTodoList = createDescriptorForTodoList();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptTodo, myConceptTodoList);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Todo:
        return myConceptTodo;
      case LanguageConceptSwitch.TodoList:
        return myConceptTodoList;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForTodo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TodoDSL", "Todo", 0x297ec2396c484eeaL, 0xbc6bbc22570d94c6L, 0x45bb23f610f047b8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:57dfd69d-4f5f-494d-9897-8ab8c7335788(TodoDSL.structure)/5024649349015029688");
    b.prop("description", 0x45bb23f610f047bbL, "5024649349015029691");
    b.prop("priority", 0x45bb23f610f047bdL, "5024649349015029693");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTodoList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TodoDSL", "TodoList", 0x297ec2396c484eeaL, 0xbc6bbc22570d94c6L, 0xc451252a9fb7bedL);
    b.class_(false, false, true);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:57dfd69d-4f5f-494d-9897-8ab8c7335788(TodoDSL.structure)/884133048096619501");
    b.prop("date", 0x45bb23f610f047abL, "5024649349015029675");
    b.prop("background", 0x45bb23f610f047adL, "5024649349015029677");
    b.aggregate("stuffToDo", 0x45bb23f610f047b6L).target(0x297ec2396c484eeaL, 0xbc6bbc22570d94c6L, 0x45bb23f610f047b8L).optional(true).ordered(true).multiple(true).origin("5024649349015029686").done();
    return b.create();
  }
}
